export const ADD_COMMENT = 'ADD_COMMENT';

export const LOAD_COMMENTS = 'LOAD_COMMENTS';
export const COMMENT_LOADING = 'COMMENT_LOADING';

export const LOAD_IMAGES = 'LOAD_IMAGES';
export const IMAGES_LOADING = 'IMAGES_LOADING';
export const IMAGES_FAILED = 'IMAGES_FAILED'

export const FILTER_IMAGES = 'FILTER_IMAGES'

export const AUTH_SUCCESS = "AUTH_SUCCESS"
export const AUTH_FAILED = "AUTH_FAILED"
export const AUTH_LOADING = "AUTH_LOADING"
export const AUTH_LOGOUT = "AUTH_LOGOUT"
